### ISSUE TITLE
Darwin support

### ISSUE THREAD

**Issue by Artturin** [trofi/nix-olde#110]
Support `darwinConfigurations` instead of `nixosConfigurations`

CC @jhulkko

**Comment by trofi** [comment]
Sounds reasonable. Should be a matter of making https://github.com/trofi/nix-olde/blob/main/src/flake.rs#L64 template conditional on the host system: `"nixosConfigurations.{}.config.system.build.toplevel.drvPath"`. Run-time or compile-time detection of the host should be fine. Maybe via `cfg(target_os = "macos")`?

**Comment by Artturin** [comment]
I'll do that, actually I was doing it yesterday but had to sleep.

**Comment by Artturin** [comment]
@jhulkko Try https://github.com/trofi/nix-olde/pull/111

`nix run github:artturin/nix-olde/macossupport`
