### ISSUE TITLE
Allow paths other then `/etc/nixos`?

### ISSUE THREAD

**Issue by doronbehar** [trofi/nix-olde#8]
Hello.

My system configuration is in `~/repos/nixos-configs`, and it's a flake based system. Running `nix-olde` I get:

```
Fetching 'repology'
Fetching 'installed'
Fetching 'available'
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at '/etc/nixos does not exist: Os { code: 2, kind: NotFound, message: "No such file or directory" }/etc/nixos does not exist: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ', src/available.rssrc/installed.rs::20:53
43note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
:61
'available' done, took 0.00 s.
'installed' done, took 0.00 s.
'repology' done, took 83.22 s.
thread 'main' panicked at 'a scoped thread panicked', src/main.rs:39:9
```

And it seems that there is no observable way to make it search for my nixos config elsewhere.

**Comment by trofi** [comment]
Yeah, right now `nix-olde` hardcodes `/etc/nixos` in a few places: https://github.com/trofi/nix-olde/blob/main/src/installed.rs#L22

I think it's worth adding ` --flake` argument by mimicking existing tools (maybe `nixos-rebuild`?)

How do you usually specify non-default flake in things like `nixos-rebuild`?

**Comment by doronbehar** [comment]
> I think it's worth adding ` --flake` argument by mimicking existing tools (maybe `nixos-rebuild`?)
> 
> How do you usually specify non-default flake in things like `nixos-rebuild`?

Just like you imagined. Here are example usages I imagine for `nix-olde`:

```
# Default to the $HOSTNAME flake
nix-olde --flake ~/repos/nixos-configs
# Specify a specific configuration
nix-olde --flake gitlab:doronbehar/nixos-configs#office
# Override flake inputs
nix-olde --flake gitlab:doronbehar/nixos-configs#home --override-input nur github:doronbehar/nur/my-fork --override-input nixpkgs github:doronbehar/nixpkgs/my-pkg-update
```

Whereas the `--override-input` flags are also supported by at least `nixos-rebuild`. Maybe the `--nixpkgs` flag should be removed / aliased to `--override-input nixpkgs`.

**Comment by trofi** [comment]
Did absolute minimum amount of plumbing in https://github.com/trofi/nix-olde/commit/f5ffced3c92818666128479a868e9fdc8f7b0e92 to at least be able to redirect from `/etc/nixos` directory.

I wonder if it makes the tool to run for you.

I'll add `.#attr` a bit later.

**Comment by doronbehar** [comment]
> I wonder if it makes the tool to run for you.

No:

```
Fetching 'repology'
Fetching 'installed'
Fetching 'available'
'installed' done, took 19.92 s.
'available' failed, took 29.58 s.
'repology' failed, took 33.62 s.

Error: MultipleErrors([Canceled("Repology fetch"), CommandFailed { cmd: ["nix-env", "-qa", "--json", "--arg", "config", "import <nixpkgs/pkgs/top-level/packages-config.nix>", "--option", "build-users-group", "\"\""], output: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "error:\n       … in the left operand of the update (//) operator\n\n         at /home/doron/.nix-defexpr/channels_root/nixos/lib/attrsets.nix:637:18:\n\n          636|   recurseIntoAttrs =\n          637|     attrs: attrs // { recurseForDerivations = true; };\n             |                  ^\n          638|\n\n       error: attribute 'zabbix60' missing\n\n       at /nix/store/jkd86nm1y8ihxh8yj9h4c366121hrgq9-source/pkgs/top-level/packages-config.nix:9:86:\n\n            8|   # purposes of the index.\n            9|   packageOverrides = super: with super; lib.mapAttrs (_: set: recurseIntoAttrs set) {\n             |                                                                                      ^\n           10|     inherit (super)\n       Did you mean one of zabbix40, zabbix50 or zabbix?\n" } }])
```

**Comment by trofi** [comment]
Aha, that is a bit of progress. This way it's slightly more readable:

"""
Error: MultipleErrors([Canceled("Repology fetch"), CommandFailed { cmd: ["nix-env", "-qa", "--json", "--arg", "config", "import <nixpkgs/pkgs/top-level/packages-config.nix>", "--option", "build-users-group", "\"\""], output: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "error:\n       … in the left operand of the update (//) operator\n\n         at /home/doron/.nix-defexpr/channels_root/nixos/lib/attrsets.nix:637:18:\n\n          636|   recurseIntoAttrs =\n          637|     attrs: attrs // { recurseForDerivations = true; };\n             |                  ^\n          638|\n\n       error: attribute 'zabbix60' missing\n\n       at /nix/store/jkd86nm1y8ihxh8yj9h4c366121hrgq9-source/pkgs/top-level/packages-config.nix:9:86:\n\n            8|   # purposes of the index.\n            9|   packageOverrides = super: with super; lib.mapAttrs (_: set: recurseIntoAttrs set) {\n             |                                                                                      ^\n           10|     inherit (super)\n       Did you mean one of zabbix40, zabbix50 or zabbix?\n" } }])
"""

I wonder why your `nixpkgs` attribute does not evaluate as is and complains about `zabbix60`. Could it be that you have invalid overlays in `.config/nixpkgs/config.nix` or similar?

A simple test would be to run something like this:

```
$ nix-env -qa --json --arg config 'import <nixpkgs/pkgs/top-level/packages-config.nix>' --option build-users-group '""' -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/master.tar.gz -f https://github.com/NixOS/nixpkgs/archive/refs/heads/master.tar.gz
```

It's expected to finish successfully and print package attributes available in `master` branch as:

```
{
  "AMB-plugins": {
    "name": "AMB-plugins-0.8.1",
    "outputName": "out",
    "outputs": {
      "out": null
    },
    "pname": "AMB-plugins",
    "system": "x86_64-linux",
    "version": "0.8.1"
  },
...
```
 If it fails let's try to figure out why.

**Comment by doronbehar** [comment]
> A simple test would be to run something like this:

That command doesn't fail and it prints a similar json. I hope that these `nixpkgs` tarballs are not injected in the code, because it doesn't make sense if someone uses their own nixpkgs fork defined in their flake.

**Comment by trofi** [comment]
> That command doesn't fail and it prints a similar json.

Aha, that's reassuring. There is probably something more subtle that is happening in your flake.

> I hope that these nixpkgs tarballs are not injected in the code, because it doesn't make sense if someone uses their own nixpkgs fork defined in their flake.

Yeah, it's not exactly what `nix-olde` does, but an approximation: the command is the same, but the path to `nixpkgs` is a local path inferred from installed system. But it's not very robust and relies on the heuristics: it looks up a flake input named `nixpkgs` (somewhat more reliable) and falls back to `<nixpkgs>` if that exists (a lot less reliable as people sometimes have `<nixpkgs>` vary quite a lot between users).

I'll try to add a bit more logging into verbose mode so it would be obvious which methods are attempted to extract local `nixpkgs` paths.

**Comment by trofi** [comment]
Try running https://github.com/trofi/nix-olde/commit/c638b6c5bd8bbb37314429ebde75e6dd1e0767a3 with `-v`. It should print all the executed commands.

For me installed packages are extracted with the following commands:

```
DEBUG: Running ["nix", "--extra-experimental-features", "nix-command", "--extra-experimental-features", "flakes", "flake", "archive", "/etc/nixos", "--json"]: ExitStatus(unix_wait_status(0))
...
DEBUG: Running ["nix-env", "-qa", "--json", "--arg", "config", "import <nixpkgs/pkgs/top-level/packages-config.nix>", "--option", "build-users-group", "\"\"", "-I", "nixpkgs=/nix/store/7ciackz23d1j54yaa57cynp0ksawrzy5-source", "-f", "/nix/store/7ciackz23d1j54yaa57cynp0ksawrzy5-source"]: ExitStatus(unix_wait_status(0))
```

`-vv` should print all command outputs, but it will be quite a bit to sift through. I hope the commands themselves should be enough to rerun manually and see why it fails to infer for you.

**Comment by doronbehar** [comment]
Thanks for the update, here's the output of it:

<details><summary> <code>nix --tarball-ttl 0 run github:trofi/nix-olde -- -v --flake repos/nixos-configs</code> </summary>

```
Fetching 'repology'
DEBUG: Fetching from repology: ""
Fetching 'installed'
Fetching 'available'
DEBUG: Running ["nix", "--extra-experimental-features", "nix-command", "--extra-experimental-features", "flakes", "flake", "archive", "/home/doron/repos/nixos-configs", "--json"]: ExitStatus(unix_wait_status(256))
DEBUG: Running ["curl", "--compressed", "https://repology.org/api/v1/projects/?inrepo=nix_unstable&outdated=1"]: ExitStatus(unix_wait_status(0))
DEBUG: Fetching from repology: "beneath-a-steel-sky/"
DEBUG: Running ["curl", "--compressed", "https://repology.org/api/v1/projects/beneath-a-steel-sky/?inrepo=nix_unstable&outdated=1"]: ExitStatus(unix_wait_status(0))
DEBUG: Fetching from repology: "cloudflare-warp/"
DEBUG: Running ["curl", "--compressed", "https://repology.org/api/v1/projects/cloudflare-warp/?inrepo=nix_unstable&outdated=1"]: ExitStatus(unix_wait_status(0))
DEBUG: Fetching from repology: "droidcam-obs/"
DEBUG: Running ["nix", "--extra-experimental-features", "nix-command", "--extra-experimental-features", "flakes", "eval", "--impure", "--raw", "/home/doron/repos/nixos-configs#nixosConfigurations.office.config.system.build.toplevel.drvPath"]: ExitStatus(unix_wait_status(0))
DEBUG: Running ["curl", "--compressed", "https://repology.org/api/v1/projects/droidcam-obs/?inrepo=nix_unstable&outdated=1"]: ExitStatus(unix_wait_status(0))
DEBUG: Fetching from repology: "fluentd/"
DEBUG: Running ["nix", "--extra-experimental-features", "nix-command", "show-derivation", "-r", "/nix/store/yjvmdhgcyg8fvqyyxbahw1z8qlpq5yql-nixos-system-office-23.11.20230725.ef99fa5.drv"]: ExitStatus(unix_wait_status(0))
'installed' done, took 12.46 s.
DEBUG: Running ["curl", "--compressed", "https://repology.org/api/v1/projects/fluentd/?inrepo=nix_unstable&outdated=1"]: ExitStatus(unix_wait_status(0))
DEBUG: Fetching from repology: "gnome:taskwhisperer/"
DEBUG: Running ["curl", "--compressed", "https://repology.org/api/v1/projects/gnome:taskwhisperer/?inrepo=nix_unstable&outdated=1"]: ExitStatus(unix_wait_status(0))
DEBUG: Fetching from repology: "haskell:amazonka-elasticache/"
DEBUG: Running ["curl", "--compressed", "https://repology.org/api/v1/projects/haskell:amazonka-elasticache/?inrepo=nix_unstable&outdated=1"]: ExitStatus(unix_wait_status(0))
DEBUG: Fetching from repology: "haskell:diohsc/"
DEBUG: Running ["curl", "--compressed", "https://repology.org/api/v1/projects/haskell:diohsc/?inrepo=nix_unstable&outdated=1"]: ExitStatus(unix_wait_status(0))
DEBUG: Fetching from repology: "haskell:lambdabot-haskell-plugins/"
DEBUG: Running ["curl", "--compressed", "https://repology.org/api/v1/projects/haskell:lambdabot-haskell-plugins/?inrepo=nix_unstable&outdated=1"]: ExitStatus(unix_wait_status(0))
DEBUG: Fetching from repology: "haskell:stb-image-redux/"
DEBUG: Running ["nix-env", "-qa", "--json", "--arg", "config", "import <nixpkgs/pkgs/top-level/packages-config.nix>", "--option", "build-users-group", "\"\""]: ExitStatus(unix_wait_status(256))
'available' failed, took 19.55 s.
DEBUG: Running ["curl", "--compressed", "https://repology.org/api/v1/projects/haskell:stb-image-redux/?inrepo=nix_unstable&outdated=1"]: ExitStatus(unix_wait_status(0))
'repology' failed, took 21.47 s.

Error: MultipleErrors([Canceled("Repology fetch"), CommandFailed { cmd: ["nix-env", "-qa", "--json", "--arg", "config", "import <nixpkgs/pkgs/top-level/packages-config.nix>", "--option", "build-users-group", "\"\""], output: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "error:\n       … in the left operand of the update (//) operator\n\n         at /home/doron/.nix-defexpr/channels_root/nixos/lib/attrsets.nix:637:18:\n\n          636|   recurseIntoAttrs =\n          637|     attrs: attrs // { recurseForDerivations = true; };\n             |                  ^\n          638|\n\n       error: attribute 'zabbix60' missing\n\n       at /nix/store/jkd86nm1y8ihxh8yj9h4c366121hrgq9-source/pkgs/top-level/packages-config.nix:9:86:\n\n            8|   # purposes of the index.\n            9|   packageOverrides = super: with super; lib.mapAttrs (_: set: recurseIntoAttrs set) {\n             |                                                                                      ^\n           10|     inherit (super)\n       Did you mean one of zabbix40, zabbix50 or zabbix?\n" } }])
```
</details>

It seems that the main difference is your `-I nixpkgs=/nix/store/...-source` and `-f /nix/store/...-source` arguments. Here is my flake's repo:

https://gitlab.com/doronbehar/nixos-configs

**Comment by trofi** [comment]
Aha, it failed to extract the path to nixpkgs from this command:

> DEBUG: Running ["nix", "--extra-experimental-features", "nix-command", "--extra-experimental-features", "flakes", "flake", "archive", "/home/doron/repos/nixos-configs", "--json"]: ExitStatus(unix_wait_status(256)

Probably because some of it's inputs are not accessible to the current user:

```
$ flake archive .# --json
fatal: '/etc/nixos/syncthing-private' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error:
       … while fetching the input 'git+file:///etc/nixos/syncthing-private?ref=refs/heads/master&rev=37c29e867275266c06ffd6be84ceebe321137f86'

       error: program 'git' failed with exit code 128
```

**Comment by doronbehar** [comment]
Aish, I see. I moved my `/etc/nixos` folder from there to `~/repos/nixos-configs` because I had permissions issues with that folder, and I forgot to fix the path to the flake. Now using a proper url, it seems to work! Thanks.

It would have been nice if `nix-olde` would have been more specific in it's error - mentioning exactly which `nix` command returned non zero exit code.

**Comment by trofi** [comment]
Yeah, that sounds very reasonable. It will require a bit of restructuring as `nix-olde` does a bit of probing for both flake and non-flake systems and would otherwise spam a bit too much.

I added a tiny hint in https://github.com/trofi/nix-olde/commit/edc610f8a7d9a17466fa09aa577b280ab097c37a.

Still need to expand support for more complete flake syntax input and show a nicer banner what `nix-olde` inferred out of system probing.

**Comment by doronbehar** [comment]
Thanks @trofi for all the work! Indeed now this works well. I tried to reproduce the issue, by pointing `nix-olde` to an old commit of my `nixos-configs` flake, and so I tried:

```
nix --option tarball-ttl 0 run github:trofi/nix-olde -- --flake gitlab:doronbehar/nixos-configs/39a5e69fdc1a5705b64d1c9d24157582b0f68362#ZENIX
```

And it did not fail. Could it be that `nix-olde` doesn't parse the last part of the flake url?

**Comment by trofi** [comment]
I think it should work, but not sure. Added the following minimal error printing by default: https://github.com/trofi/nix-olde/commit/9ea7a525e06a0feb865bd0dc998a172b0f17714b

It prints the following for your command:

```
$ LANG=C nix run .# -- --flake gitlab:doronbehar/nixos-configs/39a5e69fdc1a5705b64d1c9d24157582b0f68362#ZENIX
INFO: Failed to canonicalize path gitlab:doronbehar/nixos-configs/39a5e69fdc1a5705b64d1c9d24157582b0f68362. Assuming flake syntax.
Fetching 'installed'
Fetching 'available'
Fetching 'repology'
INFO: Failed running ["nix", "--extra-experimental-features", "nix-command", "--extra-experimental-features", "flakes", "flake", "archive", "gitlab:doronbehar/nixos-configs/39a5e69fdc1a5705b64d1c9d24157582b0f68362", "--json"]: ExitStatus(unix_wait_status(256))
INFO: Result of ["nix", "--extra-experimental-features", "nix-command", "--extra-experimental-features", "flakes", "flake", "archive", "gitlab:doronbehar/nixos-configs/39a5e69fdc1a5705b64d1c9d24157582b0f68362", "--json"]: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "\r\u{1b}[Kfatal: '/etc/nixos/syncthing-private' does not appear to be a git repository\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\r\u{1b}[Kerror:\n       … while fetching the input 'git+file:///etc/nixos/syncthing-private?ref=refs/heads/master&rev=37c29e867275266c06ffd6be84ceebe321137f86'\n\n       error: program 'git' failed with exit code 128\n" }
```

Still a `/etc/nixos/syncthing-private` repo. It is referred in https://gitlab.com/doronbehar/nixos-configs/-/blob/39a5e69fdc1a5705b64d1c9d24157582b0f68362/flake.nix#L4 in that commit. Failure looks intended (at least for me).

I wonder what failure you see now.

**Comment by doronbehar** [comment]
> I wonder what failure you see now.

I am not sure, but what bothers me is that I _don't_ see any failure :). Perhaps my `/nix/store` still has that flake source, and that's why it is possible for it to be evaluated. I propose this because that flake hasn't changed it's source hash in the commits that fixed the `syncthing-private.url` to a valid url. Hence perhaps it's not a real issue with `nix-olde`, and this could be closed :)

Thanks for all the work and help so far :). This tool is very valuable :rocket: .

**Comment by trofi** [comment]
Let's declare it done then as you got something running. I'll try to make a few related improvements separately.
