### ISSUE TITLE
Needs support added for non-standard config file locations.

### ISSUE THREAD

**Issue by guttermonk** [trofi/nix-olde#85]
My flake is saved in ~/.dotfiles/flake.nix and my configuration.nix file is in ~/.dotfiles/nixos and my home-manager config is in ~/.dotfiles/home/home.nix.

```
Fetching 'installed'
Fetching 'repology'
Fetching 'available'
INFO: Failed running ["nix", "--extra-experimental-features", "nix-command", "--extra-experimental-features", "flakes", "flake", "archive", "/etc/nixos", "--json"]: ExitStatus(unix_wait_status(256))
INFO: err> path '/etc/nixos' does not contain a 'flake.nix', searching up
INFO: err> error: could not find a flake.nix file
INFO: err> path '/etc/nixos' does not contain a 'flake.nix', searching up
INFO: err> error: could not find a flake.nix file
```

A configuration file for nix-olde where you could set the paths for the NixOS, home-manager, and flake config files may be a possible solution.

**Comment by trofi** [comment]
Aha, `~/.dotfiles/flake.nix` is a system flake, right? Does `$ nix run github:trofi/nix-olde -- --flake $HOME/.dotfiles` just work for you? Or it still fails?

What parameters do you have to pass to `nixos-rebuild` to work on your system? Ideally I would like `nix-olde` to follow that interface.

**Comment by guttermonk** [comment]
I usually run: 
```
cd ~/.dotfiles  
sudo nixos-rebuild switch --flake .#hyprnix 
```
Where .#hyprnix is what I named my configuration in my flake.nix file.

**Comment by guttermonk** [comment]
Good news! I just tried:
`nix run github:trofi/nix-olde -- --flake $HOME/.dotfiles/.#hyprnix`

And that worked.
